# readthedocs.yml

version: 2

# Default
formats: []

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

python:
  version: 3.8
  install:
    - method: pip
      path: .

conda:
  environment: devtools/conda-envs/test_env.yaml