name: Docs

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # Run a cron job once weekly on Tuesday
    - cron: "0 0 * * TUE"

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.7"
          mamba-version: "*"
          activate-environment: test
          channel-priority: true
          environment-file: devtools/conda-envs/test_env.yaml
          auto-activate-base: false

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a
      - name: Install package
        shell: bash -l {0}
        run: |
          pip install . --no-deps -vv
      - name: Environment Information
        shell: bash -l {0}
        run: |
          conda info --all
          conda list
      - name: Run Sphinx
        shell: bash -l {0}
        run: |
          cd docs
          make clean
          SPHINXOPTS="-j2 -T --keep-going" make html
